const express = require('express');
const { Octokit } = require('@octokit/rest');
const crypto = require('crypto');

const app = express();
app.use(express.json());

// Configuration
const PORT = process.env.PORT || 3000;
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const WEBHOOK_SECRET = process.env.WEBHOOK_SECRET;
const GITHUB_API_URL = process.env.GITHUB_API_URL || 'https://github.ibm.com/api/v3';

const octokit = new Octokit({
  auth: GITHUB_TOKEN,
  baseUrl: GITHUB_API_URL
});

// Verify webhook signature
function verifySignature(req) {
  const signature = req.headers['x-hub-signature-256'];
  if (!signature) return false;
  
  const hmac = crypto.createHmac('sha256', WEBHOOK_SECRET);
  const digest = 'sha256=' + hmac.update(JSON.stringify(req.body)).digest('hex');
  
  return crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(digest));
}

// Analyze code and generate review
async function analyzeCode(owner, repo, prNumber) {
  try {
    // Get PR files
    const { data: files } = await octokit.pulls.listFiles({
      owner,
      repo,
      pull_number: prNumber
    });

    let issues = [];
    
    // Check each file
    for (const file of files) {
      if (file.filename.endsWith('.java')) {
        // Get file content
        const { data: content } = await octokit.repos.getContent({
          owner,
          repo,
          path: file.filename,
          ref: file.sha
        });
        
        const code = Buffer.from(content.content, 'base64').toString('utf-8');
        const lines = code.split('\n');
        
        // Check for System.out.println
        lines.forEach((line, index) => {
          if (line.includes('System.out.println')) {
            issues.push({
              file: file.filename,
              line: index + 1,
              type: 'System.out.println',
              message: 'Consider using a logger instead of System.out.println'
            });
          }
          
          // Check for TODO
          if (line.includes('TODO')) {
            issues.push({
              file: file.filename,
              line: index + 1,
              type: 'TODO',
              message: 'TODO comment found - consider creating an issue'
            });
          }
          
          // Check for printStackTrace
          if (line.includes('printStackTrace')) {
            issues.push({
              file: file.filename,
              line: index + 1,
              type: 'printStackTrace',
              message: 'Use proper logging instead of printStackTrace'
            });
          }
        });
      }
    }
    
    return issues;
  } catch (error) {
    console.error('Error analyzing code:', error);
    return [];
  }
}

// Generate review comment
function generateReviewComment(issues) {
  let comment = '## 🔍 Automated Code Review\n\n';
  
  if (issues.length === 0) {
    comment += '✅ No issues found! Great job!\n\n';
  } else {
    comment += `Found ${issues.length} issue(s):\n\n`;
    
    const groupedIssues = {};
    issues.forEach(issue => {
      if (!groupedIssues[issue.type]) {
        groupedIssues[issue.type] = [];
      }
      groupedIssues[issue.type].push(issue);
    });
    
    Object.keys(groupedIssues).forEach(type => {
      comment += `### ⚠️ ${type}\n\n`;
      groupedIssues[type].forEach(issue => {
        comment += `- **${issue.file}:${issue.line}** - ${issue.message}\n`;
      });
      comment += '\n';
    });
  }
  
  comment += '### 💡 General Recommendations\n\n';
  comment += '- Add input validation in controllers\n';
  comment += '- Implement proper exception handling\n';
  comment += '- Add unit tests for new code\n';
  comment += '- Use environment variables for secrets\n';
  comment += '\n---\n';
  comment += '*This is an automated review. Generated by webhook server.*\n';
  
  return comment;
}

// Webhook endpoint
app.post('/webhook', async (req, res) => {
  // Verify signature
  if (!verifySignature(req)) {
    console.log('Invalid signature');
    return res.status(401).send('Invalid signature');
  }
  
  const event = req.headers['x-github-event'];
  const payload = req.body;
  
  console.log(`Received ${event} event`);
  
  // Handle pull request events
  if (event === 'pull_request') {
    const action = payload.action;
    
    if (action === 'opened' || action === 'synchronize' || action === 'reopened') {
      const owner = payload.repository.owner.login;
      const repo = payload.repository.name;
      const prNumber = payload.pull_request.number;
      
      console.log(`Analyzing PR #${prNumber} in ${owner}/${repo}`);
      
      // Analyze code
      const issues = await analyzeCode(owner, repo, prNumber);
      
      // Post comment
      const comment = generateReviewComment(issues);
      
      try {
        await octokit.issues.createComment({
          owner,
          repo,
          issue_number: prNumber,
          body: comment
        });
        
        console.log(`Posted review comment on PR #${prNumber}`);
      } catch (error) {
        console.error('Error posting comment:', error);
      }
    }
  }
  
  res.status(200).send('OK');
});

// Health check
app.get('/health', (req, res) => {
  res.status(200).json({ status: 'ok', timestamp: new Date().toISOString() });
});

// Start server
app.listen(PORT, () => {
  console.log(`Webhook server listening on port ${PORT}`);
  console.log(`GitHub API URL: ${GITHUB_API_URL}`);
  console.log('Waiting for webhook events...');
});

// Made with Bob
